name: PrcCore
version: '${version}'
main: org.beobma.prccore.PrcCore
api-version: '1.20'
commands:
  starttimeflow:
    description: 튜토리얼 종료 후 시간 흐름을 시작합니다.
    usage: /starttimeflow
    permission: prccore.command.starttimeflow
  prctest:
    description: PRC 코어 테스트/디버그 명령어
    usage: /prctest <timeflow|nextday|clearores|killmobs|setmineprogress>
    permission: prccore.command.prctest
permissions:
  prccore.command.starttimeflow:
    default: false
  prccore.command.prctest:
    default: false